class LocalDBKeys {
  LocalDBKeys._();
  // static const String enableBiometric = 'enableBiometric';
  // static const String themeMode = 'theme_mode';
  // static const String language = 'language';
  // static const String currentUser = 'currentUser';
  // static const String logHistory = 'logHistory';
  // static const String rememberMe = 'RememberMe';
  // static const String authDB="auth";
  // static const String autoGenerated="autoGenerated";
  // static const String token="token";
  // static const String productionModel='productionModel';
  static const String userBoxName = 'userBox';
}
